### ISSUE TITLE
Scheduled Task created incorrectly

### ISSUE THREAD

**Issue by ahk97** [aloopkin/WinCertes#18]
The scheduled task is created with spaces missing in the parameters, so it is not working.

**To Reproduce**
run
WinCertes.exe -d sub1.domain.com -d sub2.domain.com -d sub3.domain.com -d sub4.domain.com -a -f c:\cert\cert.ps1 -p -t 30

Check the scheduled tasks.
It will be created as
WinCertes.exe
with parameters:
-d sub1.domain.com-d sub2.domain.com-d sub3.domain.com-d sub4.domain.com 
(spaces before -d are missing, additional parameters (scripts, etc.) are missing)

**Expected behavior**
The  task should be created as
WinCertes.exe 
With parameters
-d sub1.domain.com -d sub2.domain.com -d sub3.domain.com -d sub4.domain.com -a -f c:\cert\cert.ps1 -t 30

**Desktop (please complete the following information):**
Windows Server  - Version 2012 R2

**Comment by aloopkin** [comment]
Hello,

This is not the expected behaviour... If you read how it works in Program.cs, the command line parameter (except domains) are written to the Registry, and then WinCertes read them from there:

- "-a" translates into "standalone" registry key
- "-t" translates into "renewalDays" registry key
- "-f" translates into "registryFile" registry key

Question is: does WinCertes behave as expected (apart from command-line syntax) ?

**Comment by ahk97** [comment]
Yes. The Registry values are written correctly.
So, expected behavior would be:

Expected behavior
The task should be created as
WinCertes.exe
With parameters
-d sub1.domain.com -d sub2.domain.com -d sub3.domain.com -d sub4.domain.com

**Comment by aloopkin** [comment]
Fixed as 80e9fb1

**Comment by aloopkin** [comment]
Released as part of v1.1.4
