### ISSUE TITLE
Only works with default C:\Inetpub\wwwroot folder

### ISSUE THREAD

**Issue by pgordinho** [aloopkin/WinCertes#22]
If a website uses non default physical path WinCertes still creates the challange file in C:\Inetpub\wwwroot . It should get that information from IIS and create de folder accordingly.

As a workaround it's possible to create the ".well-known" folder in C:\inetpub\wwwroot\ and add the virtual directory ".well-known" in the site, pointing to C:\inetpub\wwwroot\.well-known.

**Comment by aloopkin** [comment]
Actually, in the current version, setting it in the registry should solve the issue (HKLM\Software\WinCertes).
Seems there's a bug in the library handling the options, will get that fixed in next release.

**Comment by aloopkin** [comment]
After making some tests, i'm not sure it was a DLL issue.

Please try with -w=C:\other\path (notice the "=", as specified in the help)

**Comment by pgordinho** [comment]
> Please try with -w=C:\other\path (notice the "=", as specified in the help)

Specifying -w=C:\other\path works fine! 

Thanks

**Comment by MarcoGiorgi** [comment]
It doesn't work for multiple site because you have to specify the full path to the website you want to get the certificate.
In example if you have the you sites in the folder c:\Webs, the flag -w=C:\Webs doesn't work. You need to specify: -w=C:\Webs\WebsiteA which is the folder that contains the website and not the root.

This is the only way I've got the app to write the .well-known folder for verification
