### ISSUE TITLE
will it work with nginx

### ISSUE THREAD

**Issue by mediacoolp** [aloopkin/WinCertes#7]
i am using ginx on windows will it work ty

**Comment by aloopkin** [comment]
yes it will work, but not automatically. you need to adapt the webroot path (-w), and probably to write a PowerShell script (launched via -f) to deploy the certificate for it.

**Comment by hobi82** [comment]
Could you please provide a working example? I have tried to go down that path and because you seem to enforce the import of the .pfx into the Microsoft Certificate Store and also delete the source file afterwards, there seems to be no way to export the private key later, since Microsoft doesn't allow the export of the private key from the cert store. Also I couldn't get your Powershell sample to work with your tool. It just does nothing so far...

Why not just provide an option to leave the .pfx file as is (without the enforced import to the MS Cert store. That would be greatly appreciated since not everybody uses IIS. Cheers

**Comment by aloopkin** [comment]
So:
- import in the MS cert store is necessary to be able to manage the renewal
- i can leave the PFX on the file system, but it won't help you since you also need the password anyway
- the powershell is the best option i could think of provided the two previous items

Can you please give me more details about what you do and that isn't working, like the command lines you typed, the content of the powershell, etc.?

**Comment by aloopkin** [comment]
See #9
